import { BaseMessage } from "@langchain/core/messages";

/**
 * Represents the classification of user intent
 * Maps user queries to specific analysis tools
 */
export type IntentType =
  | "analyze_spending" // Analyze spending patterns in categories
  | "check_budget" // Check budget status and projections
  | "detect_anomalies" // Find unusual spending patterns
  | "predict_spending" // Get spending predictions
  | "view_trends" // View historical trends
  | "general_question" // General financial question
  | "unclear"; // Unable to classify

/**
 * Metrics tracked during agent execution
 */
export interface ExecutionMetrics {
  model: string;
  latencyMs: number;
  inputTokens: number;
  outputTokens: number;
  costUsd: number;
  toolCalls: number;
}

/**
 * Main state object for LangGraph agent execution
 * Flows through Router → Tool Executor → Synthesizer nodes
 */
export interface AgentState {
  /**
   * Conversation history
   * Includes user and assistant messages for context
   */
  messages: BaseMessage[];

  /**
   * Current user message being processed
   */
  userMessage: string;

  /**
   * User ID from authentication
   */
  userId: string;

  /**
   * Detected intent classification
   * Set by Router node
   */
  intent: IntentType | null;

  /**
   * Tool names to execute
   * Selected by Router based on intent
   */
  toolsToCall: string[];

  /**
   * Results from tool execution
   * Key: tool name, Value: {success: boolean, data?: T, error?: string}
   */
  toolResults: Record<string, unknown>;

  /**
   * Final response in natural language
   * Generated by Synthesizer node
   */
  finalResponse: string | null;

  /**
   * Execution metrics for monitoring
   */
  metrics: ExecutionMetrics;
}

/**
 * Tool result structure
 */
export interface ToolResult {
  success: boolean;
  data?: unknown;
  error?: string;
}
