-- MIGRATION: Add expense subcategory (Fase 2.B)
-- DATE: 2026-09-14
-- DESCRIPTION:
-- Adds an optional `subcategory` column to `expenses` as a second, more
-- specific classification layer on top of the four existing Kakebo
-- categories (survival/optional/culture/extra). The four categories are
-- NOT modified, replaced, or renamed by this migration.
--
-- - Nullable: historical expenses keep subcategory = NULL. This migration
--   performs NO backfill of existing rows.
-- - Restricted via CHECK constraint to the approved catalog defined in
--   src/lib/subcategories.ts (SUBCATEGORY_IDS) — the single source of
--   truth for the taxonomy on the application side. Extending the catalog
--   in the future requires a NEW migration that updates this CHECK
--   constraint to match the updated TypeScript list (do not edit this file
--   after it has been applied anywhere).
--
-- SAFETY: this migration has NOT been run against any Supabase project by
-- the assistant. Idempotent: safe to run more than once (uses IF NOT
-- EXISTS / guarded DO blocks throughout). Run it in the Supabase SQL
-- Editor (or via the Supabase CLI) of the target project when the owner
-- decides to close Fase 2.

-- 1. Add the column (nullable, no default — historical rows stay NULL,
--    no backfill is performed here).
ALTER TABLE IF EXISTS public.expenses
  ADD COLUMN IF NOT EXISTS subcategory text;

-- 2. Restrict future values to the approved catalog. Guarded so it is safe
--    to re-run: only adds the constraint if it does not already exist.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'expenses_subcategory_check'
      AND conrelid = 'public.expenses'::regclass
  ) THEN
    ALTER TABLE public.expenses
      ADD CONSTRAINT expenses_subcategory_check
      CHECK (
        subcategory IS NULL OR subcategory IN (
          'food_basic',
          'dining_out',
          'housing',
          'utilities',
          'transport',
          'health',
          'education',
          'subscriptions',
          'personal_shopping',
          'leisure',
          'travel',
          'gifts',
          'fees_taxes',
          'other'
        )
      );
  END IF;
END $$;

-- 3. Index to speed up exact subcategory filters (searchExpenses, Fase 2.B).
--    Partial index: skips NULL rows (the majority of historical data).
CREATE INDEX IF NOT EXISTS idx_expenses_subcategory
  ON public.expenses (user_id, subcategory)
  WHERE subcategory IS NOT NULL;

-- 4. Audit trail / self-documentation.
COMMENT ON COLUMN public.expenses.subcategory IS
  'Fase 2.B: optional second-layer classification, independent of the 4 Kakebo categories. NULL = unclassified (historical rows, or not set by the user/AI). Values restricted by expenses_subcategory_check to the catalog defined in src/lib/subcategories.ts (SUBCATEGORY_IDS) — keep both in sync.';
